baseURL = "http://example.org/"
languageCode = "en-us"
title = "INTALInC - Capítulo Latinoamérica"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/
 
# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Integrantes"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Capacidades"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "Galería"
        url     = "gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contacto"
        url     = "contact"
        weight  = 6

# Site Params
[params]
    home = "Inicio"
    logo = "images/logo.jpg"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"
 
    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Bienvenido a INTALInC-LAC"
        description = "Somos una red de investigadores que promueven los sistemas de transporte urbano que puedan satisfacer las necesidades de comunidades con bajos ingresos en Latinoamérica."
        btn     = true
        btnText = "Nuestro Libro"
        btnURL  = "https://www.dropbox.com/s/xrk29wyp5joojfd/transporte%20urbano.pdf?dl=0"
        [[params.banner.flipText]]
            title   = "Transporte"
        [[params.banner.flipText]]
            title   = "Equidad"
        [[params.banner.flipText]]
            title   = "Justicia Social"
        [[params.banner.flipText]]
            title   = "Caminabilidad"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "Sobre Nosotros"
        content = "Queremos proporcionar evidencia que asegure que cada ser humano tengo derecho a una mobilidad económica, segura, limpia y confiable. INTALInC-LAC hace parte de INATALInC, una red con más de 20 socios y 200 miembros individuales establecida en el 2017. <br/> Este es el capítulo para Latinoamérica de INTALInC y busca juntar investigadores de diferentes campos, personas trabajando en el diseño o implementación de políticas públicas, activistas y en general, personas interesadas en estudiar los problemas de la región y que quieran hacer parte de las soluciones. "
        image   = "images/about/about.jpg" 

    # Call to Action
    [params.cta]
        enable  = true
        title   = "¿Deseas colaborar con nosotros?"
        content = "Siempre estamos buscando conocer nuevos proyectos y personas interesadas en promover una agenda de sostenibilidad y equidad"
        btnText = "¡Ponte en contacto!"
        btnURL  = "/contact"
 
    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Últimos Trabajos"
        subtitle= "Nuestra red trabaja principalmente en Latinoamércia y todo el Sur Global haciendo parte de proyectos de investigación, consultoría, activismo o en actividades académicas."

    
